{
  "type": "record",
  "name": "SubmitPaymentCommand",
  "namespace": "com.ilchern.saasbilling.contracts.messaging.payment",
  "fields": [
    {
      "name": "metadata",
      "type": "com.ilchern.saasbilling.contracts.messaging.MessageMetadata"
    },
    { "name": "invoiceId", "type": "string" },
    { "name": "subscriptionId", "type": "string" },
    { "name": "organizationId", "type": "string" },
    { "name": "amountMinor", "type": "long" },
    { "name": "currency", "type": "string" },
    { "name": "paymentMethodToken", "type": "string" }
  ]
}
