spring:
  application:
    name: billing-orchestrator
  datasource:
    url: jdbc:postgresql://localhost:5434/orchestrator_service_db
    username: orchestrator_service_user
    password: orchestrator_service_password
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
      enable-auto-commit: false
      max-poll-records: 10
      isolation-level: read_committed
    properties:
      schema.registry.url: http://localhost:8081

orchestrator:
  kafka:
    topics:
      subscription-events: subscription.events
      billing-events: billing.events
  sagas:
    initial-subscription-billing:
      start-event: SubscriptionCreatedEvent
      initial-status: STARTED
      business-key-path: $.payload.subscriptionId
      transitions:
        - from: STARTED
          "on": SubscriptionCreatedEvent
          to: INITIAL_INVOICE_REQUESTED
          emit:
            topic: billing.commands
            type: CreateInitialInvoice
        - from: INITIAL_INVOICE_REQUESTED
          "on": InvoiceCreatedEvent
          to: PAYMENT_REQUESTED
          emit:
            topic: payment.commands
            type: SubmitPayment
            aggregate-id-path: $.payload.invoiceId

server:
  port: 8085
