spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/reactive_chat_service
    redis:
      host: localhost
      port: 6379

chat:
  # 0 means Runtime.availableProcessors()
  session-worker-pool-size: 0
  rate-limit:
    enabled: true
    key-prefix: chat:rate-limit:user
    capacity: 20
    refill-tokens: 20
    refill-period: 1s
    ttl: 2m
