SERVER:
  PORT: 8084

SPRING:
  APPLICATION:
    NAME: billing-service
  DATASOURCE:
    URL: jdbc:postgresql://billing-postgres:5432/billing_service_db
    USERNAME: billing_service_user
    PASSWORD: billing_service_password
  KAFKA:
    BOOTSTRAP_SERVERS: kafka:9092
    PROPERTIES:
      SCHEMA:
        REGISTRY:
          URL: http://schema-registry:8081

BILLING:
  KAFKA:
    DLT:
      RETRY:
        BACKOFF_MS: 1000
        MAX_ATTEMPTS: 3
    TOPICS:
      COMMANDS:
        NAME: billing.commands
      COMMANDS_DLT:
        NAME: billing.commands.dlt
      EVENTS:
        NAME: billing.events
